name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls
        pip install -r local-requirements.txt
        pip install -e .
    - name: Lint
      run: |
        black --check .
        mypy .
        flake8 pytest_playwright tests
    - name: Test with pytest
      run: pytest --cov=pytest_playwright --cov-report xml
    - name: Coveralls
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
